# Dados da conexão
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_ac?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=SUA_SENHA_AQUI

# Mostrar o que o Spring está fazendo no banco
spring.jpa.show-sql=true

# Cria as tabelas automaticamente baseado nas classes Java que vamos criar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect